language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.2
    - android-26

#Based on:
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
# https://docs.travis-ci.com/user/languages/android/